#ifndef exe_h
#define exe_h

void add(void);
void addi(void);
void addiu(void);
void addu(void);
void andd(void);
void andi(void);
void beq(void);
void bgez(void);
void bgezal(void);
void bgtz(void);
void blez(void);
void bltz(void);
void bltzal(void);
void bne(void);
void j(void);
void jal(void);
void jr(void);
void lb(void);
void lui(void);
void lbu(void);
void lh(void);
void lhu(void);
void lw(void);
void nor(void);
void orr(void);
void ori(void);
void sb(void);
void sh(void);
void sll(void);
void sllv(void);
void slt(void);
void slti(void);
void sltiu(void);
void sltu(void);
void srl(void);
void srlv(void);
void sub(void);
void subu(void);
void sw(void);
void xorr(void);
void xori(void);
void movn(void);
void movz(void);
void seb(void);
#endif
